"""empty message

Revision ID: 21ab299d9e0f
Revises: 2ffb381ac6ec
Create Date: 2023-12-20 16:27:38.492549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ab299d9e0f'
down_revision = '2ffb381ac6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_voted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
